---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sample-app-project
  source:
    repoURL: https://github.com/pushpendrasingh3/wf_action_01.git
    targetRevision: HEAD
    path: argocd-cicd-setup/dev
  destination:
    #server: https://kubernetes.default.svc
    server: https://34.47.198.97
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
